services:
  db:
    image: postgres:9.5
    volumes:
      - "${HOME}/docker/volumes/postgres:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: "on-failure"

  grafana:
    depends_on:
      - db
    image: grafana/grafana:9.0.2
    volumes:
      - ./hosts/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
